name: bluetooth_print
description: A new flutter plugin project connect to bluetooth thermal printer (Gprinter).
version: 2.0.0
homepage: https://github.com/thon-ju/bluetooth_print

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.1
  json_serializable: ^6.11.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.example.bluetooth_print
    pluginClass: BluetoothPrintPlugin

